CREATE TABLE users (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    phone           VARCHAR(15) UNIQUE NOT NULL,
    email           VARCHAR(255) UNIQUE,
    full_name       VARCHAR(100) NOT NULL,
    password_hash   TEXT,
    avatar_url      TEXT,
    gender          VARCHAR(10) CHECK (gender IN ('male', 'female', 'other')),
    home_location   GEOGRAPHY(POINT, 4326),
    home_address    TEXT,
    office_location GEOGRAPHY(POINT, 4326),
    office_address  TEXT,
    default_role    VARCHAR(10) DEFAULT 'both' CHECK (default_role IN ('driver', 'rider', 'both')),
    preferences     JSONB DEFAULT '{}'::jsonb,
    is_phone_verified  BOOLEAN DEFAULT FALSE,
    is_email_verified  BOOLEAN DEFAULT FALSE,
    is_id_verified     BOOLEAN DEFAULT FALSE,
    total_rides        INT DEFAULT 0,
    total_co2_saved_kg DECIMAL(10,2) DEFAULT 0,
    rating_avg         DECIMAL(3,2) DEFAULT 5.00,
    rating_count       INT DEFAULT 0,
    city_id            UUID REFERENCES cities(id),
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);